### ISSUE TITLE
would you please add some offline demo?

### ISSUE THREAD

**Issue by wywzxxz** [gl-vis/gl-surface3d#1]
This project is awesome, but it's setup bepuzzle me. 
First I guess it works in node-webkit , then
   a)meet a ERROR "cairo/cairo.h: No such file or directory" when npm install
          I guess it's relay on GTK+ and Cairo ?
   b) web page http://mikolalysenko.github.io/gl-surface-plot worked even offline.
          I found it works when I place it at the example folder . however if I replace suface,js and correspondingly changes require("../surface.js") to require("./surface.js") ,It failed.
          this confuse me. Why did it happened?besides,is this surface works in the front? But it seems that browser don't support require.
           so would you please add some offline demo? I think it will be great helpful

**Comment by mikolalysenko** [comment]
You should look at [gl-plot3d](http://github.com/gl-vis/gl-plot3d) for some examples on how to set this up.  This is all sort of an early work in progress, so apologies for any mess as it is right now.  Things should be getting easier to use as time goes on.
