### ISSUE TITLE
Surface refresh on update

### ISSUE THREAD

**Issue by kevinjos** [gl-vis/gl-surface3d#2]
@mikolalysenko thanks for this great library.

Perhaps I am not using the API correctly. I create a scene, add this surface to the scene, and update the surface with a new field. The issue I am having is that the image in the browser does not show the changes to the surface unless I mouse over the surface. Is there a way to update the surface image in browser every time that surface.update({'field': myfield}) is called?

Thanks,
Kevin

**Comment by mikolalysenko** [comment]
Probably a bug!  This is still pretty early, and so lots of these things are in flux.  Thanks for reporting it, I will probably look at it sometime next week and get a fix out.

**Comment by kevinjos** [comment]
Very good, thank you. I will stay tuned.

**Comment by mikolalysenko** [comment]
Should be fixed in the newest version.
